language: node_js
sudo: false
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: UzYdrbzz7qvU5dF1xSNgo14yX1iZj2o3qoSvtncpMwkewAML9jDZr9cdgiupDJ5DcOLhvD8wpEYIQqqpFhKeDj+Cwz24mX293IBaHOlbwKgPV1ynm9aFBkfDSAk5PMivPemELY/3rT+d8OBFl852Y6D5YvoLSYts/FRqGAPyGBw=
  file:
    - 'dale-chall.js'
    - 'dale-chall.min.js'
  on:
    tags: true
